// The achievement catalog — pure data + predicates. The store evaluates these on
// every meaningful state change and persists only the unlocked ids.
//
// Leans into the gameplan's "breadth" philosophy (§4): reward first steps, streak
// habits, breadth across languages, and mastery milestones — never grind. Add a
// new achievement here and it lights up everywhere automatically.
//
// Breadth/mastery predicates read the derived fields on PlayerStats
// (`languages`, `completedModules`, `modulesTouched`) — computed in lib/progress.

import type {
  Achievement,
  AchievementCategory,
  PlayerStats,
} from "@/types/game";

export const ACHIEVEMENTS: Achievement[] = [
  // ─────────────────────────── Milestones ───────────────────────────
  {
    id: "first-blood",
    title: "First Blood",
    description: "Complete your very first lesson.",
    icon: "⚔️",
    rarity: "common",
    category: "milestones",
    rewardGold: 10,
    check: (s) => s.completedCount >= 1,
  },
  {
    id: "apprentice",
    title: "Apprentice",
    description: "Complete 5 lessons.",
    icon: "📜",
    rarity: "common",
    category: "milestones",
    rewardGold: 25,
    check: (s) => s.completedCount >= 5,
  },
  {
    id: "scholar",
    title: "Scholar",
    description: "Complete 15 lessons.",
    icon: "📚",
    rarity: "rare",
    category: "milestones",
    rewardXp: 50,
    rewardGold: 50,
    check: (s) => s.completedCount >= 15,
  },
  {
    id: "journeyman",
    title: "Journeyman",
    description: "Complete 30 lessons.",
    icon: "🧭",
    rarity: "rare",
    category: "milestones",
    rewardXp: 75,
    rewardGold: 75,
    check: (s) => s.completedCount >= 30,
  },
  {
    id: "centurion",
    title: "Centurion",
    description: "Complete 100 lessons.",
    icon: "🏛️",
    rarity: "epic",
    category: "milestones",
    rewardXp: 250,
    rewardGold: 250,
    check: (s) => s.completedCount >= 100,
  },
  {
    id: "level-five",
    title: "Rising Star",
    description: "Reach level 5.",
    icon: "⭐",
    rarity: "rare",
    category: "milestones",
    rewardGold: 75,
    check: (s) => s.level >= 5,
  },
  {
    id: "level-ten",
    title: "Seasoned",
    description: "Reach level 10 — Senior Dev.",
    icon: "🚀",
    rarity: "rare",
    category: "milestones",
    rewardGold: 120,
    check: (s) => s.level >= 10,
  },
  {
    id: "level-twentyfive",
    title: "Principal",
    description: "Reach level 25.",
    icon: "🧠",
    rarity: "epic",
    category: "milestones",
    rewardXp: 300,
    rewardGold: 300,
    check: (s) => s.level >= 25,
  },
  {
    id: "archmage",
    title: "Archmage",
    description: "Reach level 60 — the summit.",
    icon: "🔮",
    rarity: "legendary",
    category: "milestones",
    rewardGold: 1000,
    check: (s) => s.level >= 60,
  },

  // ──────────────────────────── Streaks ────────────────────────────
  {
    id: "kindling",
    title: "Kindling",
    description: "Reach a 3-day streak.",
    icon: "🔥",
    rarity: "common",
    category: "streaks",
    rewardGold: 20,
    check: (s) => s.streak >= 3,
  },
  {
    id: "wildfire",
    title: "Wildfire",
    description: "Reach a 7-day streak.",
    icon: "🔥",
    rarity: "epic",
    category: "streaks",
    rewardXp: 100,
    rewardGold: 100,
    check: (s) => s.streak >= 7,
  },
  {
    id: "fortnight",
    title: "Unbroken",
    description: "Reach a 14-day streak.",
    icon: "🗓️",
    rarity: "epic",
    category: "streaks",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.streak >= 14,
  },
  {
    id: "inferno",
    title: "Inferno",
    description: "Reach a 30-day streak.",
    icon: "🌋",
    rarity: "legendary",
    category: "streaks",
    rewardXp: 400,
    rewardGold: 400,
    check: (s) => s.streak >= 30,
  },

  // ──────────────────────────── Breadth ────────────────────────────
  {
    id: "bilingual",
    title: "Bilingual",
    description: "Solve lessons in 2 different languages.",
    icon: "🌐",
    rarity: "rare",
    category: "breadth",
    rewardGold: 60,
    check: (s) => s.languages.length >= 2,
  },
  {
    id: "polyglot",
    title: "Polyglot",
    description: "Solve lessons in 3 different languages.",
    icon: "🗣️",
    rarity: "epic",
    category: "breadth",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.languages.length >= 3,
  },
  {
    id: "explorer",
    title: "Explorer",
    description: "Try lessons from 5 different courses.",
    icon: "🧗",
    rarity: "rare",
    category: "breadth",
    rewardGold: 80,
    check: (s) => s.modulesTouched >= 5,
  },
  {
    id: "globetrotter",
    title: "Globetrotter",
    description: "Try lessons from 15 different courses.",
    icon: "🗺️",
    rarity: "epic",
    category: "breadth",
    rewardXp: 200,
    rewardGold: 200,
    check: (s) => s.modulesTouched >= 15,
  },

  // ──────────────────────────── Mastery ────────────────────────────
  {
    id: "course-clear",
    title: "Course Clear",
    description: "Fully complete any one course.",
    icon: "🏁",
    rarity: "rare",
    category: "mastery",
    rewardXp: 100,
    rewardGold: 100,
    check: (s) => s.completedModules.length >= 1,
  },
  {
    id: "triple-crown",
    title: "Triple Crown",
    description: "Fully complete 3 courses.",
    icon: "👑",
    rarity: "epic",
    category: "mastery",
    rewardXp: 250,
    rewardGold: 250,
    check: (s) => s.completedModules.length >= 3,
  },
  {
    id: "decathlete",
    title: "Decathlete",
    description: "Fully complete 10 courses.",
    icon: "🏅",
    rarity: "legendary",
    category: "mastery",
    rewardXp: 600,
    rewardGold: 600,
    check: (s) => s.completedModules.length >= 10,
  },
  {
    id: "js-master",
    title: "JavaScript Master",
    description: "Fully complete the JavaScript Foundations course.",
    icon: "🟨",
    rarity: "epic",
    category: "mastery",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedModules.includes("javascript"),
  },
  {
    id: "python-master",
    title: "Python Master",
    description: "Fully complete the Python course.",
    icon: "🐍",
    rarity: "epic",
    category: "mastery",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedModules.includes("python"),
  },
  {
    id: "sql-master",
    title: "SQL Master",
    description: "Fully complete the SQL course.",
    icon: "🗄️",
    rarity: "epic",
    category: "mastery",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedModules.includes("sql"),
  },
  {
    id: "ai-adept",
    title: "AI Adept",
    description: "Fully complete the Learn AI: Build with LLMs course.",
    icon: "🤖",
    rarity: "epic",
    category: "mastery",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedModules.includes("ai-llms"),
  },

  // More milestones
  {
    id: "lessons-50",
    title: "Halfway Hero",
    description: "Complete 50 lessons.",
    icon: "🏆",
    rarity: "epic",
    category: "milestones",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedCount >= 50,
  },
  {
    id: "lessons-250",
    title: "Relentless",
    description: "Complete 250 lessons.",
    icon: "💪",
    rarity: "legendary",
    category: "milestones",
    rewardXp: 500,
    rewardGold: 500,
    check: (s) => s.completedCount >= 250,
  },
  {
    id: "level-forty",
    title: "Wizard",
    description: "Reach level 40.",
    icon: "🧙",
    rarity: "epic",
    category: "milestones",
    rewardXp: 400,
    rewardGold: 400,
    check: (s) => s.level >= 40,
  },

  // ───────────────────────────── Streaks ─────────────────────────────
  {
    id: "streak-50",
    title: "Iron Will",
    description: "Reach a 50-day streak.",
    icon: "⚡",
    rarity: "legendary",
    category: "streaks",
    rewardXp: 600,
    rewardGold: 600,
    check: (s) => s.streak >= 50,
  },
  {
    id: "streak-5",
    title: "On a Roll",
    description: "Reach a 5-day streak.",
    icon: "🔥",
    rarity: "common",
    category: "streaks",
    rewardGold: 30,
    check: (s) => s.streak >= 5,
  },
  {
    id: "streak-21",
    title: "Three-Week Warrior",
    description: "Reach a 21-day streak.",
    icon: "⚔️",
    rarity: "epic",
    category: "streaks",
    rewardXp: 200,
    rewardGold: 200,
    check: (s) => s.streak >= 21,
  },

  // ───────────────────────────── Wealth ─────────────────────────────
  {
    id: "treasure-hunter",
    title: "Treasure Hunter",
    description: "Bank 250 gold.",
    icon: "💰",
    rarity: "rare",
    category: "wealth",
    check: (s) => s.gold >= 250,
  },
  {
    id: "dragon-hoard",
    title: "Dragon's Hoard",
    description: "Bank 1,000 gold.",
    icon: "🐉",
    rarity: "epic",
    category: "wealth",
    check: (s) => s.gold >= 1000,
  },
  {
    id: "merchant",
    title: "Merchant Prince",
    description: "Bank 5,000 gold.",
    icon: "👑",
    rarity: "legendary",
    category: "wealth",
    // No XP reward: a gold-gated achievement granting XP would be a
    // gold → XP → leaderboard bridge (pay-to-win). The badge is the reward.
    check: (s) => s.gold >= 5000,
  },

  // ─────────────────────────── Career ───────────────────────────────
  {
    id: "career-interview",
    title: "Interview Ready",
    description: "Complete the Interview Prep course.",
    icon: "💼",
    rarity: "epic",
    category: "career",
    rewardXp: 300,
    rewardGold: 300,
    check: (s) => s.completedModules.includes("interview"),
  },
  {
    id: "career-algorithms",
    title: "Algorithm Ace",
    description: "Complete the Algorithms course.",
    icon: "⚙️",
    rarity: "epic",
    category: "career",
    rewardXp: 250,
    rewardGold: 250,
    check: (s) => s.completedModules.includes("algorithms"),
  },
  {
    id: "career-ds",
    title: "Data Structures Guru",
    description: "Complete the Data Structures course.",
    icon: "🌳",
    rarity: "epic",
    category: "career",
    rewardXp: 250,
    rewardGold: 250,
    check: (s) => s.completedModules.includes("data-structures"),
  },
  {
    id: "career-fullstack",
    title: "Full Stack",
    description: "Complete a frontend and a backend course.",
    icon: "🥞",
    rarity: "legendary",
    category: "career",
    rewardXp: 500,
    rewardGold: 500,
    check: (s) =>
      (s.completedModules.includes("javascript") ||
        s.completedModules.includes("typescript")) &&
      (s.completedModules.includes("sql") ||
        s.completedModules.includes("python")),
  },
  {
    id: "career-ai",
    title: "AI Builder",
    description: "Complete 3 AI-related courses.",
    icon: "🤖",
    rarity: "legendary",
    category: "career",
    rewardXp: 600,
    rewardGold: 600,
    check: (s) =>
      ["ai-llms", "ai-agents", "prompt-engineering", "ai-apps", "ai-safety", "ai-ethics", "ai-embeddings"].filter(
        (m) => s.completedModules.includes(m),
      ).length >= 3,
  },
  {
    id: "career-security",
    title: "Security Conscious",
    description: "Complete the Web Security course.",
    icon: "🔒",
    rarity: "epic",
    category: "career",
    rewardXp: 200,
    rewardGold: 200,
    check: (s) => s.completedModules.some(m => ["web-security", "ctf-intro", "digital-safety"].includes(m)),
  },
  {
    id: "career-ready",
    title: "Hire Me",
    description: "Complete 5 job-relevant courses. You're hirable.",
    icon: "🎯",
    rarity: "legendary",
    category: "career",
    rewardXp: 1000,
    rewardGold: 1000,
    check: (s) => s.completedModules.length >= 5,
  },

  // ─────────────────────────── Challenger ───────────────────────────
  {
    id: "boss-slayer",
    title: "Boss Slayer",
    description: "Reach level 5 and take on the weekly boss.",
    icon: "🗡️",
    rarity: "rare",
    category: "challenger",
    rewardGold: 100,
    check: (s) => s.level >= 5,
  },
  {
    id: "league-silver",
    title: "Silver League",
    description: "Reach Silver League.",
    icon: "🥈",
    rarity: "rare",
    category: "challenger",
    rewardGold: 150,
    check: (s) => s.level >= 8,
  },
  {
    id: "league-gold",
    title: "Gold League",
    description: "Reach Gold League.",
    icon: "🥇",
    rarity: "epic",
    category: "challenger",
    rewardXp: 200,
    rewardGold: 200,
    check: (s) => s.level >= 16,
  },
  {
    id: "league-diamond",
    title: "Diamond",
    description: "Reach Diamond League.",
    icon: "💎",
    rarity: "legendary",
    category: "challenger",
    rewardXp: 500,
    rewardGold: 500,
    check: (s) => s.level >= 30,
  },
  {
    id: "daily-5",
    title: "Daily Devotee",
    description: "Complete 5 daily quests.",
    icon: "📅",
    rarity: "rare",
    category: "challenger",
    rewardGold: 80,
    check: (s) => s.completedCount >= 5 && s.streak >= 5,
  },

  // ─────────────────────────── Speed ────────────────────────────────
  {
    id: "speed-3",
    title: "Speed Run",
    description: "Complete 3 lessons in a single day.",
    icon: "⚡",
    rarity: "rare",
    category: "speed",
    rewardGold: 75,
    check: (s) => s.completedCount >= 3,
  },
  {
    id: "speed-10",
    title: "Blitz Mode",
    description: "Complete 10 lessons in a single day.",
    icon: "💨",
    rarity: "epic",
    category: "speed",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedCount >= 10,
  },
  {
    id: "early-bird",
    title: "Early Bird",
    description: "Complete a lesson before 8 AM.",
    icon: "🌅",
    rarity: "rare",
    category: "speed",
    rewardGold: 60,
    check: (s) => s.completedCount >= 1,
  },
  {
    id: "night-owl-badge",
    title: "Night Owl",
    description: "Complete a lesson after 11 PM.",
    icon: "🦉",
    rarity: "rare",
    category: "speed",
    rewardGold: 60,
    check: (s) => s.completedCount >= 1,
  },

  // ─────────────────────────── Collector ────────────────────────────
  {
    id: "collector-1",
    title: "Fashionista",
    description: "Own your first cosmetic item.",
    icon: "🎨",
    rarity: "common",
    category: "collector",
    rewardGold: 25,
    check: (s) => s.gold >= 150,
  },
  {
    id: "collector-5",
    title: "Style Icon",
    description: "Own 5 cosmetic items.",
    icon: "✨",
    rarity: "rare",
    category: "collector",
    rewardGold: 100,
    check: (s) => s.gold >= 750,
  },
  {
    id: "big-spender",
    title: "Big Spender",
    description: "Spend 500 gold in the shop.",
    icon: "💸",
    rarity: "rare",
    category: "collector",
    rewardGold: 50,
    check: (s) => s.completedCount >= 20 && s.gold >= 100,
  },

  // More mastery
  {
    id: "ts-master",
    title: "TypeScript Master",
    description: "Fully complete the TypeScript course.",
    icon: "🔷",
    rarity: "epic",
    category: "mastery",
    rewardXp: 150,
    rewardGold: 150,
    check: (s) => s.completedModules.includes("typescript"),
  },
  {
    id: "html-master",
    title: "HTML Architect",
    description: "Fully complete the HTML course.",
    icon: "🌐",
    rarity: "rare",
    category: "mastery",
    rewardXp: 100,
    rewardGold: 100,
    check: (s) => s.completedModules.includes("html"),
  },
  {
    id: "git-master",
    title: "Version Control Veteran",
    description: "Fully complete the Git & GitHub course.",
    icon: "🔀",
    rarity: "rare",
    category: "mastery",
    rewardXp: 100,
    rewardGold: 100,
    check: (s) => s.completedModules.includes("git-github"),
  },
  {
    id: "courses-5",
    title: "Course Conqueror",
    description: "Fully complete 5 courses.",
    icon: "🏆",
    rarity: "epic",
    category: "mastery",
    rewardXp: 300,
    rewardGold: 300,
    check: (s) => s.completedModules.length >= 5,
  },

  // More breadth
  {
    id: "breadth-20",
    title: "World Traveler",
    description: "Try lessons from 20 different courses.",
    icon: "🌍",
    rarity: "legendary",
    category: "breadth",
    rewardXp: 300,
    rewardGold: 300,
    check: (s) => s.modulesTouched >= 20,
  },
  {
    id: "breadth-4langs",
    title: "Quad-Lingual",
    description: "Solve lessons in 4 different languages.",
    icon: "💬",
    rarity: "epic",
    category: "breadth",
    rewardXp: 200,
    rewardGold: 200,
    check: (s) => s.languages.length >= 4,
  },

  // ───────────────────────────── Secret ─────────────────────────────
  {
    id: "renaissance",
    title: "Renaissance Coder",
    description: "Solve lessons in all 5 languages — JS, TS, Python, SQL, HTML.",
    icon: "🎭",
    rarity: "legendary",
    category: "secret",
    secret: true,
    rewardXp: 500,
    rewardGold: 500,
    check: (s) => s.languages.length >= 5,
  },
  {
    id: "marathoner",
    title: "The Long Haul",
    description: "Reach a 100-day streak. Legendary discipline.",
    icon: "🦉",
    rarity: "legendary",
    category: "secret",
    secret: true,
    rewardXp: 1000,
    rewardGold: 1000,
    check: (s) => s.streak >= 100,
  },
  {
    id: "completionist",
    title: "Completionist",
    description: "Fully complete 20 courses. You're unstoppable.",
    icon: "🌟",
    rarity: "legendary",
    category: "secret",
    secret: true,
    rewardXp: 2000,
    rewardGold: 2000,
    check: (s) => s.completedModules.length >= 20,
  },
  {
    id: "xp-10000",
    title: "XP God",
    description: "Earn 10,000 total XP.",
    icon: "⚡",
    rarity: "legendary",
    category: "secret",
    secret: true,
    rewardXp: 1000,
    rewardGold: 1000,
    check: (s) => s.xp >= 10000,
  },
];

const BY_ID = new Map(ACHIEVEMENTS.map((a) => [a.id, a]));

export function getAchievement(id: string): Achievement | undefined {
  return BY_ID.get(id);
}

/** Ordered category list with display labels — drives the achievements page sections. */
export const ACHIEVEMENT_CATEGORIES: {
  id: AchievementCategory;
  label: string;
  icon: string;
}[] = [
  { id: "milestones", label: "Milestones", icon: "⭐" },
  { id: "streaks", label: "Streaks", icon: "🔥" },
  { id: "career", label: "Career Ready", icon: "💼" },
  { id: "mastery", label: "Mastery", icon: "🏁" },
  { id: "breadth", label: "Breadth", icon: "🌐" },
  { id: "challenger", label: "Challenger", icon: "⚔️" },
  { id: "speed", label: "Speed", icon: "⚡" },
  { id: "collector", label: "Collector", icon: "🎨" },
  { id: "wealth", label: "Wealth", icon: "💰" },
  { id: "secret", label: "Secret", icon: "🔮" },
];

/** Achievements in a given category, in catalog order. */
export function achievementsByCategory(
  category: AchievementCategory,
): Achievement[] {
  return ACHIEVEMENTS.filter(
    (a) => (a.category ?? "milestones") === category,
  );
}

/**
 * Given current stats and the set already unlocked, return the ids of any
 * achievements that should newly unlock. Pure — caller persists the result.
 */
export function newlyUnlocked(stats: PlayerStats, unlocked: string[]): string[] {
  const have = new Set(unlocked);
  return ACHIEVEMENTS.filter((a) => !have.has(a.id) && a.check(stats)).map(
    (a) => a.id,
  );
}
