// CLIENT-SAFE catalog. Importing this pulls in only catalog.data.json (display
// metadata + lesson ids/titles, ~160 KB) plus the tiny tracks + ids helpers — it
// NEVER drags lesson bodies/tests/solutions into the browser bundle the way the
// curriculum barrel (index.ts → all 149 module files) does.
//
// Use this in any "use client" component that needs course/lesson METADATA
// (titles, counts, ids, track grouping, progress math). Components that need full
// lesson CONTENT (the lesson runner, review session) still import the barrel and
// are intentionally route-scoped.
//
// catalog.data.json is generated by scripts/gen-catalog.ts and kept fresh by
// `npm run check`; never edit it by hand.

import data from "./catalog.data.json";
import { groupByTrack, type Track } from "./tracks";
import { lessonId } from "./ids";

export { lessonId };

export type CatalogLesson = {
  slug: string;
  title: string;
  blurb: string;
  xp: number;
  /** Resolved lesson language (lesson override ?? module language ?? "js"). */
  language: string;
  /** Canonical completion id "moduleSlug/lessonSlug". */
  id: string;
};

export type CatalogModule = {
  slug: string;
  title: string;
  description: string;
  tagline: string;
  emoji: string;
  gradient: string;
  language: string;
  keywords: string[];
  trackId: string | null;
  lessonCount: number;
  lessons: CatalogLesson[];
};

export type CatalogTrackGroup = { track: Track; modules: CatalogModule[] };

export const CATALOG = data.modules as CatalogModule[];
export const CATALOG_TOTALS = data.totals as {
  moduleCount: number;
  lessonCount: number;
  xpAvailable: number;
};

const BY_SLUG = new Map(CATALOG.map((m) => [m.slug, m]));

/** Lightweight equivalent of getModule — returns metadata only (no lessons[] bodies). */
export function getCatalogModule(slug: string): CatalogModule | undefined {
  return BY_SLUG.get(slug);
}

/** Track-grouped catalog for the /learn browser and the dashboard. */
export function catalogByTrack(): CatalogTrackGroup[] {
  return groupByTrack(CATALOG);
}

export const totalModuleCount = CATALOG_TOTALS.moduleCount;
export const totalLessonCount = CATALOG_TOTALS.lessonCount;
export const totalXpAvailable = CATALOG_TOTALS.xpAvailable;
