import type { CheatSheet } from "./types";

export const pythonCheatsheet: CheatSheet = {
  slug: "python",
  title: "Python Cheat Sheet",
  language: "Python",
  emoji: "🐍",
  description:
    "A quick-reference Python cheat sheet covering variables, strings, lists, dicts, comprehensions, functions, and more.",
  keywords: [
    "python cheat sheet",
    "python cheatsheet",
    "python syntax reference",
    "python basics",
  ],
  sections: [
    {
      title: "Variables & Types",
      items: [
        { code: "x = 42", desc: "Assign an integer" },
        { code: "pi = 3.14", desc: "Assign a float" },
        { code: "name = 'Ada'", desc: "Assign a string" },
        { code: "ok = True", desc: "Assign a boolean" },
        { code: "nothing = None", desc: "The null/absent value" },
        { code: "type(x)", desc: "Get the type of a value" },
        { code: "a, b = 1, 2", desc: "Tuple unpacking into two names" },
        { code: "isinstance(x, int)", desc: "Check if x is an int" },
      ],
    },
    {
      title: "Strings & f-strings",
      items: [
        { code: "f'Hi {name}, you are {age}'", desc: "Interpolate values into a string" },
        { code: "f'{price:.2f}'", desc: "Format a number to 2 decimals" },
        { code: "'abc'.upper()", desc: "Uppercase a string" },
        { code: "'  hi  '.strip()", desc: "Trim surrounding whitespace" },
        { code: "'a,b,c'.split(',')", desc: "Split into a list on a delimiter" },
        { code: "'-'.join(['a', 'b'])", desc: "Join a list into one string" },
        { code: "'cat' in text", desc: "Check substring membership" },
        { code: "text.replace('a', 'b')", desc: "Replace all occurrences" },
      ],
    },
    {
      title: "Numbers & Math",
      items: [
        { code: "7 // 2", desc: "Integer (floor) division -> 3" },
        { code: "7 % 2", desc: "Modulo (remainder) -> 1" },
        { code: "2 ** 10", desc: "Exponentiation -> 1024" },
        { code: "abs(-5)", desc: "Absolute value" },
        { code: "round(3.567, 1)", desc: "Round to 1 decimal place" },
        { code: "min(3, 9, 1)", desc: "Smallest of the arguments" },
        { code: "sum([1, 2, 3])", desc: "Sum of an iterable" },
        { code: "int('42')", desc: "Parse a string to an int" },
      ],
    },
    {
      title: "Lists",
      items: [
        { code: "nums = [1, 2, 3]", desc: "Create a list" },
        { code: "nums[0]", desc: "First element (zero-indexed)" },
        { code: "nums[-1]", desc: "Last element" },
        { code: "nums[1:3]", desc: "Slice items at index 1 and 2" },
        { code: "nums[::-1]", desc: "Reversed copy via slicing" },
        { code: "len(nums)", desc: "Number of items" },
        { code: "3 in nums", desc: "Membership test" },
        { code: "list(range(5))", desc: "Build [0, 1, 2, 3, 4]" },
      ],
    },
    {
      title: "List Methods",
      items: [
        { code: "nums.append(4)", desc: "Add an item to the end" },
        { code: "nums.extend([5, 6])", desc: "Append all items from an iterable" },
        { code: "nums.insert(0, 9)", desc: "Insert at a given index" },
        { code: "nums.pop()", desc: "Remove and return the last item" },
        { code: "nums.remove(2)", desc: "Remove first matching value" },
        { code: "nums.sort()", desc: "Sort in place ascending" },
        { code: "sorted(nums, reverse=True)", desc: "Return a new descending list" },
        { code: "nums.index(3)", desc: "Find index of first match" },
      ],
    },
    {
      title: "Dictionaries",
      items: [
        { code: "user = {'name': 'Ada', 'age': 36}", desc: "Create a dict" },
        { code: "user['name']", desc: "Access a value by key" },
        { code: "user.get('email', 'n/a')", desc: "Safe lookup with a default" },
        { code: "user['email'] = 'a@b.com'", desc: "Add or update a key" },
        { code: "del user['age']", desc: "Delete a key" },
        { code: "user.keys()", desc: "View of all keys" },
        { code: "user.items()", desc: "View of (key, value) pairs" },
        { code: "{**a, **b}", desc: "Merge two dicts into a new one" },
      ],
    },
    {
      title: "Comprehensions",
      items: [
        { code: "[x * 2 for x in nums]", desc: "Map each item to a new list" },
        { code: "[x for x in nums if x > 0]", desc: "Filter items with a condition" },
        { code: "[x * y for x in a for y in b]", desc: "Nested loops in one list" },
        { code: "{x for x in nums}", desc: "Set comprehension (unique values)" },
        { code: "{k: v for k, v in pairs}", desc: "Build a dict from pairs" },
        { code: "{w: len(w) for w in words}", desc: "Map words to their length" },
        { code: "(x * x for x in nums)", desc: "Lazy generator expression" },
        { code: "[y for row in grid for y in row]", desc: "Flatten a 2D list" },
      ],
    },
    {
      title: "Functions & Default Args",
      items: [
        { code: "def add(a, b):\n    return a + b", desc: "Define a function" },
        { code: "def greet(name='world'):", desc: "Parameter with a default value" },
        { code: "add(b=2, a=1)", desc: "Call using keyword arguments" },
        { code: "def total(*args):", desc: "Accept any number of positional args" },
        { code: "def cfg(**kwargs):", desc: "Accept arbitrary keyword args" },
        { code: "square = lambda x: x * x", desc: "Anonymous (lambda) function" },
        { code: "def area(w: int) -> int:", desc: "Add type hints to a function" },
        { code: "return a, b", desc: "Return multiple values as a tuple" },
      ],
    },
    {
      title: "Conditionals & Loops",
      items: [
        { code: "if x > 0:\n    ...\nelif x == 0:\n    ...\nelse:\n    ...", desc: "Branching with elif/else" },
        { code: "label = 'pos' if x > 0 else 'neg'", desc: "Ternary (conditional) expression" },
        { code: "for item in nums:", desc: "Iterate over a sequence" },
        { code: "for i, v in enumerate(nums):", desc: "Loop with index and value" },
        { code: "for k, v in user.items():", desc: "Loop over dict key/value pairs" },
        { code: "for a, b in zip(xs, ys):", desc: "Iterate two sequences in parallel" },
        { code: "for i in range(0, 10, 2):", desc: "Range with start, stop, step" },
        { code: "while n > 0:\n    n -= 1", desc: "Loop while a condition holds" },
      ],
    },
    {
      title: "Classes",
      items: [
        { code: "class Dog:", desc: "Define a class" },
        { code: "def __init__(self, name):\n    self.name = name", desc: "Constructor sets instance state" },
        { code: "def bark(self):\n    return f'{self.name}!'", desc: "Define an instance method" },
        { code: "d = Dog('Rex')", desc: "Create an instance" },
        { code: "d.name", desc: "Access an attribute" },
        { code: "class Pup(Dog):", desc: "Inherit from a base class" },
        { code: "super().__init__(name)", desc: "Call the parent constructor" },
        { code: "def __repr__(self):", desc: "Customize the debug string" },
      ],
    },
  ],
};
