// Generates supabase/seed.sql from the repo curriculum so server-side scoring
// (complete_lesson RPC) knows the canonical XP for every lesson. Run with:
//   npm run seed:sql
// then apply supabase/seed.sql to your Supabase project (SQL editor or db push).
import { writeFileSync } from "node:fs";
import { MODULES } from "./_modules.ts";

const esc = (s: string) => s.replace(/'/g, "''");

let sql =
  "-- AUTO-GENERATED by scripts/seed-curriculum-sql.ts — do not edit by hand.\n" +
  "-- Seeds courses + lessons so public.complete_lesson() has canonical XP.\n" +
  "-- Re-run `npm run seed:sql` whenever the curriculum changes.\n\n";

MODULES.forEach((m, mi) => {
  sql +=
    `insert into public.courses (slug, title, description, emoji, gradient, tagline, sort_order)\n` +
    `values ('${esc(m.slug)}', '${esc(m.title)}', '${esc(m.description)}', '${m.emoji}', '${esc(m.gradient)}', '${esc(m.tagline)}', ${mi})\n` +
    `on conflict (slug) do update set title=excluded.title, description=excluded.description, ` +
    `emoji=excluded.emoji, gradient=excluded.gradient, tagline=excluded.tagline, sort_order=excluded.sort_order;\n`;

  m.lessons.forEach((l, li) => {
    sql +=
      `insert into public.lessons (course_id, slug, title, blurb, xp, sort_order)\n` +
      `values ((select id from public.courses where slug='${esc(m.slug)}'), '${esc(l.slug)}', '${esc(l.title)}', '${esc(l.blurb)}', ${l.xp}, ${li})\n` +
      `on conflict (course_id, slug) do update set title=excluded.title, blurb=excluded.blurb, xp=excluded.xp, sort_order=excluded.sort_order;\n`;
  });
  sql += "\n";
});

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(
  `Wrote supabase/seed.sql — ${MODULES.length} courses, ${MODULES.reduce((n, m) => n + m.lessons.length, 0)} lessons.`,
);
